name: ci

on:
  push:
    branches:
    
main

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      
uses: actions/checkout@v4
name: Set up java 17
    uses: actions/setup-java@v3
    with:
      distribution: 'adopt'
      java-version: '17'
name: Compile ParfumeappApplication
  run: mvn compile
name: Test ParfumeappApplication
run: mvn test