name: teszta

on:
  push:
    branches:
      - master

env:
  DOCKER_REGISTRY: ghcr.io
  DOCKER_IMAGE_NAME: ${{ github.repository }}

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up java 22
        uses: actions/setup-java@v3
        with:
          distribution: 'adopt'
          java-version: '22'
      - name: Compile TesztaappApplication
        run: mvn compile
      - name: Test TesztaappApplication
        run: mvn test
      - name: Publish package
        run: mvn --batch-mode deploy --file pom.xml
        env:
          GITHUB_TOKEN: ${{ secrets.AUTOAPI_SECRET }}